name       : inxi
version    : 3.2.01
release    : 26
source     :
    - https://github.com/smxi/inxi/archive/3.2.01-1.tar.gz : 5949170421249ef9c88abe577cca0487ad77195b8b0bea4a6ade1211efee85e5
homepage   : https://smxi.org/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
rundeps    :
    - bind-utils
    - dmidecode
    - lm_sensors
    - mesa-demos
    - xdpyinfo
    - xrandr
install    : |
    install -Dm00755 inxi -t $installdir/usr/bin
    install -Dm00644 inxi.1 -t $installdir/usr/share/man/man1
