name        : inxi
version     : 2.2.35
release     : 9
source      :
    - https://github.com/smxi/inxi/tarball/8a3c62c : 3818df70f0eb30ac27dfc969692db1f5aea04a03f44a87e5bb84bf59bf2940c0
homepage    : http://code.google.com/p/inxi/
license     : GPL-3.0+
summary     : System info script for irc (forked from infobash by locsmif)
description : |
    Inxi is a system information script can display all kinds of things about your hardware and software to users in an IRC (Internet Relay Chat) chatroom. It runs with the /exec command in most irc clients and also /cmd with konversation and /inxi in quassel.
install    : |
    install -D inxi %installroot%/usr/bin/inxi
