name       : inxi
version    : 2.3.19
release    : 13
source     :
    - https://github.com/smxi/inxi/tarball/99eef9e : 335fcd289acde8006df262a9d21ca2d2886777f35aca6848fdd891e498727d41
homepage   : https://github.com/smxi/inxi
license    : GPL-3.0
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
rundeps    :
    - bind-utils
    - dmidecode
install    : |
    install -Dm00755 inxi $installdir/usr/bin/inxi
