name       : inxi
version    : 3.3.20
release    : 39
source     :
    - https://github.com/smxi/inxi/archive/refs/tags/3.3.20-1.tar.gz : 610b7cd60b1ca3df091c51f3ed80d73b1ed57f4be10007f40dc7487bfb2bb4af
homepage   : https://smxi.org/docs/inxi.htm
license    : GPL-3.0-or-later
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
mancompress: yes
rundeps    :
    - bind-utils
    - dmidecode
    - lm_sensors
    - mesa-demos
    - perl-json-xs
    - smartmontools
    - xdpyinfo
    - xprop
    - xrandr
install    : |
    install -Dm00755 inxi -t $installdir/usr/bin
    install -Dm00644 inxi.1 -t $installdir/usr/share/man/man1
