name       : inxi
version    : 3.3.16
release    : 35
source     :
    - https://github.com/smxi/inxi/archive/refs/tags/3.3.16-1.tar.gz : aa8e1e181e34505b4c9404122306624d644dbc50acce000257a9e94b203066cd
homepage   : https://smxi.org/docs/inxi.htm
license    : GPL-3.0-or-later
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
rundeps    :
    - bind-utils
    - dmidecode
    - lm_sensors
    - mesa-demos
    - perl-json-xs
    - smartmontools
    - xdpyinfo
    - xprop
    - xrandr
install    : |
    install -Dm00755 inxi -t $installdir/usr/bin
    install -Dm00644 inxi.1 -t $installdir/usr/share/man/man1
