name       : inxi
version    : 2.3.1
release    : 10
source     :
    - https://github.com/smxi/inxi/tarball/56d21a1 : b259a9a53af34c36789df61d940a90d75676d3adac3a5f2b5918448d62359651
homepage   : http://code.google.com/p/inxi/
license    : GPL-3.0
component  : system.utils
summary    : System info script for irc (forked from infobash by locsmif)
description: |
    Inxi is a system information script can display all kinds of things about your hardware and software to users in an IRC (Internet Relay Chat) chatroom. It runs with the /exec command in most irc clients and also /cmd with konversation and /inxi in quassel.
install    : |
    install -D inxi %installroot%/usr/bin/inxi
