name       : inxi
version    : 2.3.38
release    : 15
source     :
    - https://github.com/smxi/inxi/tarball/c245556 : d385fc6c176f79de944281bc8ccfc068218a295ba44fc6bd93f032cb8ec44beb
homepage   : https://github.com/smxi/inxi
license    : GPL-3.0
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
rundeps    :
    - bind-utils
    - dmidecode
setup      : |
    # Disable self updater
    sed -i "s/B_ALLOW_UPDATE='true'/B_ALLOW_UPDATE='false'/" inxi
    # Correct shebang
    sed -i 's|/usr/bin/env bash|/bin/bash|' inxi
install    : |
    install -Dm00755 inxi $installdir/usr/bin/inxi
    install -Dm00644 inxi.1.gz $installdir/usr/man/man1/inxi.1.gz
