name       : inxi
version    : 3.0.29
release    : 19
source     :
    - https://github.com/smxi/inxi/archive/3.0.29-1.tar.gz : f6037e668933f2028b67ce12e80ea662dec3d3c20d260d26dc1d9ab86f75803c
homepage   : https://github.com/smxi/inxi
license    : GPL-3.0-or-later
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
rundeps    :
    - bind-utils
    - dmidecode
    - lm_sensors
    - mesa-demos
    - xdpyinfo
    - xrandr
install    : |
    install -D -m 00755 inxi $installdir/usr/bin/inxi
    install -D -m 00644 inxi.1 $installdir/usr/man/man1/inxi.1
