name       : inxi
version    : 3.3.26
release    : 45
source     :
    - https://github.com/smxi/inxi/archive/refs/tags/3.3.26-1.tar.gz : 9c76b90044a5840d9e32fd83d1b3c1bb0d7c39c89904ac387cf6be339785451e
homepage   : https://smxi.org/docs/inxi.htm
license    : GPL-3.0-or-later
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
mancompress: yes
rundeps    :
    - bind-utils
    - dmidecode
    - lm_sensors
    - mesa-demos
    - perl-json-xs
    - smartmontools
    - xdpyinfo
    - xprop
    - xrandr
install    : |
    install -Dm00755 inxi -t $installdir/usr/bin
    install -Dm00644 inxi.1 -t $installdir/usr/share/man/man1
