name       : inxi
version    : 2.3.23
release    : 14
source     :
    - https://github.com/smxi/inxi/tarball/3aafcbe : 369bd61efab25c5b9d2e43b86757d3778408ead7de55e9442fa68220e9dcaf8d
homepage   : https://github.com/smxi/inxi
license    : GPL-3.0
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
rundeps    :
    - bind-utils
    - dmidecode
setup      : |
    # Disable self updater
    sed -i "s/B_ALLOW_UPDATE='true'/B_ALLOW_UPDATE='false'/" inxi
    # Correct shebang
    sed -i 's|/usr/bin/env bash|/bin/bash|' inxi
install    : |
    install -Dm00755 inxi $installdir/usr/bin/inxi
    install -Dm00644 inxi.1.gz $installdir/usr/man/man1/inxi.1.gz
