name       : inxi
version    : 3.1.00
release    : 24
source     :
    - https://github.com/smxi/inxi/archive/3.1.00-1.tar.gz : ee6675489467cbfb90756db9aaf55da4bc5f7506cc8166d3a42ba28963e810f1
homepage   : https://smxi.org/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
rundeps    :
    - bind-utils
    - dmidecode
    - lm_sensors
    - mesa-demos
    - xdpyinfo
    - xrandr
install    : |
    install -Dm00755 inxi $installdir/usr/bin/inxi
    install -Dm00644 inxi.1 $installdir/usr/man/man1/inxi.1
