name       : inxi
version    : 3.0.32
release    : 20
source     :
    - https://github.com/smxi/inxi/archive/3.0.32-1.tar.gz : aadd0ee54d0710520fc89a61378cfabfbad54f479a228107af9398e243cfea9d
homepage   : https://github.com/smxi/inxi
license    : GPL-3.0-or-later
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
rundeps    :
    - bind-utils
    - dmidecode
    - lm_sensors
    - mesa-demos
    - xdpyinfo
    - xrandr
install    : |
    install -D -m 00755 inxi $installdir/usr/bin/inxi
    install -D -m 00644 inxi.1 $installdir/usr/man/man1/inxi.1
