name       : inxi
version    : 3.3.27
release    : 47
source     :
    - https://github.com/smxi/inxi/archive/refs/tags/3.3.27-1.tar.gz : 35207195579261ddfe59508fdc92d40902c91230084d2b98b4541a6f4c682f63
homepage   : https://smxi.org/docs/inxi.htm
license    : GPL-3.0-or-later
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
mancompress: yes
rundeps    :
    - bind-utils
    - dmidecode
    - lm_sensors
    - mesa-demos
    - pciutils
    - perl-json-xs
    - smartmontools
    - xdpyinfo
    - xprop
    - xrandr
install    : |
    install -Dm00755 inxi -t $installdir/usr/bin
    install -Dm00644 inxi.1 -t $installdir/usr/share/man/man1
