name       : inxi
version    : 3.0.37
release    : 23
source     :
    - https://github.com/smxi/inxi/archive/3.0.37-1.tar.gz : bc16d8b975a8ed064949bc8209e0c01c204c01c9046076f62709366e672bea40
homepage   : https://smxi.org/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
rundeps    :
    - bind-utils
    - dmidecode
    - lm_sensors
    - mesa-demos
    - xdpyinfo
    - xrandr
install    : |
    install -Dm00755 inxi $installdir/usr/bin/inxi
    install -Dm00644 inxi.1 $installdir/usr/man/man1/inxi.1
