name       : inxi
version    : 3.0.20
release    : 17
source     :
    - https://github.com/smxi/inxi/archive/3.0.20-1.tar.gz : 0f60466dfbbe0fe7b7a870572124fb1eb7cb74a3cf11198427a86d3f4746f11a
homepage   : https://github.com/smxi/inxi
license    : GPL-3.0-or-later
component  : system.utils
summary    : Command line system information tool
description: |
    Inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and also runs somewhat on BSDs.
rundeps    :
    - bind-utils
    - dmidecode
    - lm_sensors
    - mesa-demos
    - xdpyinfo
    - xrandr
install    : |
    install -D -m 00755 inxi $installdir/usr/bin/inxi
    install -D -m 00644 inxi.1 $installdir/usr/man/man1/inxi.1
